#!/usr/bin/env bash
# OpenClaw single-command installer
# Usage: bash install.sh
set -euo pipefail

OPENCLAW_DIR="$HOME/.openclaw"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_DIR="$SCRIPT_DIR/config"

echo "============================================"
echo "  OpenClaw Installer"
echo "============================================"
echo ""

# ── Preflight checks ──────────────────────────────────────
command -v docker >/dev/null 2>&1 || { echo "ERROR: Docker is not installed. Install Docker Desktop first."; exit 1; }
docker info >/dev/null 2>&1 || { echo "ERROR: Docker is not running. Start Docker Desktop first."; exit 1; }

# ── Collect secrets ───────────────────────────────────────
echo "── API Keys ──"
echo "(Leave blank to skip optional integrations)"
echo ""

read -rp "Mistral API key (recommended): " MISTRAL_KEY
read -rp "Fathom API key (optional): " FATHOM_KEY
read -rp "HubSpot access token (optional): " HUBSPOT_TOKEN

echo ""
echo "── Slack Setup ──"
echo "1. Go to https://api.slack.com/apps → Create New App → From manifest"
echo "2. Paste contents of: $CONFIG_DIR/slack-app-manifest.json"
echo "3. Install to workspace"
echo ""
read -rp "Slack Bot Token (xoxb-...): " SLACK_BOT_TOKEN
read -rp "Slack App Token (xapp-...): " SLACK_APP_TOKEN
read -rp "Your Slack User ID (Profile → ⋯ → Copy member ID): " SLACK_USER_ID

echo ""
echo "── Gmail & Calendar ──"
read -rp "Gmail address for gog CLI (or blank to skip): " GOG_ACCOUNT

# ── Generate gateway token ────────────────────────────────
GATEWAY_TOKEN=$(openssl rand -hex 24 2>/dev/null || python3 -c "import secrets; print(secrets.token_hex(24))" 2>/dev/null || echo "change-me-$(date +%s)")

# ── Create directory structure ────────────────────────────
echo ""
echo "── Setting up $OPENCLAW_DIR ──"
mkdir -p "$OPENCLAW_DIR/workspace/skills"
mkdir -p "$OPENCLAW_DIR/bin"
mkdir -p "$OPENCLAW_DIR/gogcli"

# ── Write .env ────────────────────────────────────────────
ENV_FILE="$CONFIG_DIR/.env"
cat > "$ENV_FILE" <<EOF
# Generated by install.sh on $(date -Iseconds 2>/dev/null || date)
SLACK_USER_ID=${SLACK_USER_ID}
GOG_ACCOUNT=${GOG_ACCOUNT:-you@gmail.com}
GOG_KEYRING_PASSWORD=openclaw-local
EOF

[ -n "$MISTRAL_KEY" ] && echo "MISTRAL_API_KEY=${MISTRAL_KEY}" >> "$ENV_FILE"
[ -n "$FATHOM_KEY" ] && echo "FATHOM_API_KEY=${FATHOM_KEY}" >> "$ENV_FILE"
[ -n "$HUBSPOT_TOKEN" ] && echo "HUBSPOT_ACCESS_TOKEN=${HUBSPOT_TOKEN}" >> "$ENV_FILE"

echo "  ✓ config/.env"

# ── Write openclaw.json ──────────────────────────────────
SLACK_USER_LOWER=$(echo "$SLACK_USER_ID" | tr '[:upper:]' '[:lower:]')

sed \
  -e "s|xoxb-YOUR-BOT-TOKEN|${SLACK_BOT_TOKEN}|g" \
  -e "s|xapp-YOUR-APP-TOKEN|${SLACK_APP_TOKEN}|g" \
  -e "s|GENERATE-A-RANDOM-TOKEN-HERE|${GATEWAY_TOKEN}|g" \
  -e "s|slack:YOUR-SLACK-USER-ID|slack:${SLACK_USER_ID}|g" \
  "$CONFIG_DIR/openclaw.reference.json" > "$OPENCLAW_DIR/openclaw.json"

echo "  ✓ openclaw.json"

# ── Copy workspace files ─────────────────────────────────
cp "$CONFIG_DIR/TOOLS.reference.md" "$OPENCLAW_DIR/workspace/TOOLS.md"
cp "$CONFIG_DIR/AGENTS.reference.md" "$OPENCLAW_DIR/workspace/AGENTS.md"
echo "  ✓ TOOLS.md, AGENTS.md"

# ── Install skills ───────────────────────────────────────
cp -r "$CONFIG_DIR/skills/"* "$OPENCLAW_DIR/workspace/skills/" 2>/dev/null || true
find "$OPENCLAW_DIR/workspace/skills" -name "*.sh" -exec chmod +x {} \;
echo "  ✓ Skills installed"

# ── Google OAuth setup (if Gmail provided) ───────────────
if [ -n "$GOG_ACCOUNT" ] && [ "$GOG_ACCOUNT" != "" ]; then
  echo ""
  echo "── Gmail/Calendar Setup ──"

  if ! command -v gog >/dev/null 2>&1; then
    echo "  gog CLI not found. Installing..."
    case "$(uname -s)" in
      Darwin*)
        ARCH=$(uname -m)
        if [ "$ARCH" = "arm64" ]; then
          GOG_URL="https://github.com/steipete/gogcli/releases/latest/download/gogcli_0.12.0_darwin_arm64.tar.gz"
        else
          GOG_URL="https://github.com/steipete/gogcli/releases/latest/download/gogcli_0.12.0_darwin_amd64.tar.gz"
        fi
        curl -sL -o /tmp/gogcli.tar.gz "$GOG_URL"
        tar -xzf /tmp/gogcli.tar.gz -C /tmp/
        mkdir -p ~/.local/bin
        cp /tmp/gog ~/.local/bin/gog
        chmod +x ~/.local/bin/gog
        export PATH="$HOME/.local/bin:$PATH"
        ;;
      MINGW*|MSYS*|CYGWIN*)
        curl -sL -o /tmp/gogcli.zip "https://github.com/steipete/gogcli/releases/latest/download/gogcli_0.12.0_windows_amd64.zip"
        unzip -o /tmp/gogcli.zip -d /tmp/gogcli >/dev/null
        mkdir -p ~/.local/bin
        cp /tmp/gogcli/gog.exe ~/.local/bin/gog.exe 2>/dev/null || cp /tmp/gogcli/gog ~/.local/bin/gog 2>/dev/null
        chmod +x ~/.local/bin/gog* 2>/dev/null
        export PATH="$HOME/.local/bin:$PATH"
        ;;
      Linux*)
        curl -sL -o /tmp/gogcli.tar.gz "https://github.com/steipete/gogcli/releases/latest/download/gogcli_0.12.0_linux_amd64.tar.gz"
        tar -xzf /tmp/gogcli.tar.gz -C /tmp/
        mkdir -p ~/.local/bin
        cp /tmp/gog ~/.local/bin/gog
        chmod +x ~/.local/bin/gog
        export PATH="$HOME/.local/bin:$PATH"
        ;;
    esac
    echo "  ✓ gog CLI installed"
  fi

  # Download Linux binary for Docker container
  echo "  Downloading Linux gog binary for container..."
  curl -sL "https://github.com/steipete/gogcli/releases/latest/download/gogcli_0.12.0_linux_amd64.tar.gz" | tar -xz -C "$OPENCLAW_DIR/bin/"
  chmod +x "$OPENCLAW_DIR/bin/gog"
  echo "  ✓ Linux gog binary"

  echo ""
  echo "  You need a Google Cloud OAuth client (Desktop app type)."
  echo "  If you don't have one yet:"
  echo "    1. Go to https://console.cloud.google.com"
  echo "    2. Enable Gmail API, Calendar API, Google Drive API"
  echo "    3. Credentials → Create OAuth 2.0 Client ID (Desktop app)"
  echo "    4. Download the client_secret JSON file"
  echo ""
  read -rp "  Path to client_secret JSON (or blank to skip): " CLIENT_SECRET

  if [ -n "$CLIENT_SECRET" ] && [ -f "$CLIENT_SECRET" ]; then
    gog auth credentials "$CLIENT_SECRET"
    gog auth add "$GOG_ACCOUNT" --services gmail,calendar,drive,docs,sheets

    # Switch to file keyring and export
    gog auth keyring file
    mkdir -p "$OPENCLAW_DIR/gogcli"
    gog auth tokens export "$GOG_ACCOUNT" --out "$OPENCLAW_DIR/gogcli/token.json"

    # Copy credentials
    if [ -d "$APPDATA/gogcli" ]; then
      cp "$APPDATA/gogcli/credentials.json" "$OPENCLAW_DIR/gogcli/" 2>/dev/null || true
    elif [ -d "$HOME/Library/Application Support/gogcli" ]; then
      cp "$HOME/Library/Application Support/gogcli/credentials.json" "$OPENCLAW_DIR/gogcli/" 2>/dev/null || true
    elif [ -d "$HOME/.config/gogcli" ]; then
      cp "$HOME/.config/gogcli/credentials.json" "$OPENCLAW_DIR/gogcli/" 2>/dev/null || true
    fi
    echo "  ✓ Google OAuth configured"
  else
    echo "  Skipping Google OAuth — you can set it up later with setup/03-integrations.md"
  fi
fi

# ── Pull and start container ─────────────────────────────
echo ""
echo "── Starting OpenClaw ──"
docker pull ghcr.io/openclaw/openclaw:latest

# Stop existing container if running
docker rm -f openclaw 2>/dev/null || true

# Detect Windows Git Bash for path mangling fix
DOCKER_PREFIX=""
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*) DOCKER_PREFIX="MSYS_NO_PATHCONV=1" ;;
esac

eval $DOCKER_PREFIX docker run -d \
  --name openclaw \
  --restart unless-stopped \
  --read-only \
  --cap-drop=ALL \
  --security-opt=no-new-privileges \
  --tmpfs /tmp \
  --tmpfs /home/node \
  --env-file "$CONFIG_DIR/.env" \
  -v "$HOME/.openclaw:/home/node/.openclaw" \
  -v "$OPENCLAW_DIR/bin/gog:/usr/local/bin/gog:ro" \
  -v "$OPENCLAW_DIR/gogcli:/home/node/.config/gogcli" \
  -p 127.0.0.1:18789:18789 \
  ghcr.io/openclaw/openclaw:latest

echo "  ✓ Container started"

# ── Import gog token if it exists ─────────────────────────
if [ -f "$OPENCLAW_DIR/gogcli/token.json" ]; then
  echo "  Importing gog token into container..."
  sleep 3  # Wait for container to initialize
  docker exec -e GOG_KEYRING_PASSWORD=openclaw-local openclaw gog auth keyring file 2>/dev/null || true
  docker exec -e GOG_KEYRING_PASSWORD=openclaw-local openclaw gog auth tokens import /home/node/.config/gogcli/token.json 2>/dev/null || true
  echo "  ✓ Google token imported"
fi

# ── Verify ────────────────────────────────────────────────
echo ""
echo "── Waiting for health check ──"
for i in $(seq 1 30); do
  STATUS=$(docker inspect --format='{{.State.Health.Status}}' openclaw 2>/dev/null || echo "starting")
  if [ "$STATUS" = "healthy" ]; then
    echo "  ✓ OpenClaw is healthy!"
    break
  fi
  sleep 2
done

echo ""
echo "============================================"
echo "  OpenClaw is running!"
echo "============================================"
echo ""
echo "  Send a DM to your bot in Slack to get started."
echo ""
echo "  Try:"
echo "    • What's on my calendar this week?"
echo "    • Who sent my last email?"
echo "    • Find calls for [company name]"
echo ""
echo "  Logs:  docker logs openclaw --tail 20"
echo "  Shell: docker exec -it openclaw openclaw tui"
echo ""
